---
# tasks file for all the machines

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Install necessary packages
  become: true
  ansible.builtin.apt:
    pkg:
    - git
    - python3
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg

- name: Set timezone to Europe/Paris
  become: true
  community.general.timezone:
    name: Europe/Paris
