---
- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Set JAVA_HOME and PATH
  copy:
    dest: /etc/profile.d/java.sh
    content: |
      export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which java)))))
      export PATH=$PATH:$JAVA_HOME/bin
    owner: root
    group: root
    mode: '0644'

- name: Source Java environment
  shell: source /etc/profile.d/java.sh
  args:
    executable: /bin/bash

- name: Add Jenkins key
  shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc
  args:
    creates: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins repository
  copy:
    dest: /etc/apt/sources.list.d/jenkins.list
    content: |
      deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
    owner: root
    group: root
    mode: '0644'

- name: Update package cache
  apt:
    update_cache: yes

- name: Upload new jenkins service
  become: true
  ansible.builtin.copy:
    src: ../files/override.conf
    mode: 600
    dest: /etc/systemd/system/jenkins.service.d/
  register: service_upload

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Add JCASC directory
  file:
    path: '/var/lib/jenkins/casc_configs'
    state: directory
  become: true

- name: Copy JCASC Config
  template:
    src: ../files/jenkins_config.yaml
    dest: /var/lib/jenkins/casc_configs/
  become: true

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
  become: true

- name: Install Jenkins plugin job-dsl
  community.general.jenkins_plugin:
    name: "job-dsl"
    state: latest
    timeout: 120

- name: Install Jenkins plugin configuration-as-code
  community.general.jenkins_plugin:
    name: "configuration-as-code"
    state: latest
    timeout: 120

- name: Install Jenkins plugin github
  community.general.jenkins_plugin:
    name: "github"
    state: latest
    timeout: 120

- name: Install Jenkins plugin role-strategy
  community.general.jenkins_plugin:
    name: "role-strategy"
    state: latest
    timeout: 120

- name: Reload Jenkins service
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: true
  become: true
