FROM node:latest

SHELL ["/bin/bash", "-c"]

ONBUILD WORKDIR /app

ONBUILD COPY app/main.bf ./main.bf

ONBUILD RUN apt-get update && apt-get install -y npm
ONBUILD RUN npm install -g befunge-interpreter

ONBUILD CMD ["befunge-interpreter", "main.bf"]
