FROM node:latest

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY app/main.bf ./main.bf

RUN apt-get update && apt-get install -y npm
RUN npm install -g befunge-interpreter

CMD ["befunge-interpreter", "main.bf"]
