FROM maven:3.9.8-eclipse-temurin-21

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY app/pom.xml ./pom.xml
COPY app/src ./src

RUN mvn package

RUN find . ! -name 'app.jar' -type f -exec rm -f {} +

CMD ["java", "-jar", "target/app.jar"]
