{{- if .Values.deployment.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loadbalancer
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  {{- range .Values.deployment.ports }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: {{ . | quote }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}
{{- end }}
