{{- if .Values.deployment.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loadbalancer
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
    {{- range $index, $port := .Values.deployment.ports }}
    - name: port-{{ $port }}
      port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
    {{- end }}
{{- end }}
