name: Whanos pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


env:
  EPITECH_REPOSITORY_LINK: "git@github.com:EpitechPromo2027/B-DOP-500-NAN-5-1-whanos-dragos.suceveanu.git"

permissions:
  contents: write

jobs:

  python-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Linter (flake8)
      run: |
        flake8 .

  deploy-documentation:
    runs-on: ubuntu-latest
    needs:
      - python-checks
    steps:
      - uses: actions/checkout@v3

      - name: Configure Wiki access
        env:
          WIKI_URL: "https://${{ secrets.GH_TOKEN }}@github.com/BxptisteM/Whanos.wiki.git"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone "$WIKI_URL" wiki

      - name: Deploy documentation to Wiki
        run: |
          rm -rf wiki/*
          cp -r docs/* wiki/
          cp README.md wiki/Home.md

      - name: Push changes to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Update Wiki documentation"
          git push

  mirroring:
    runs-on: ubuntu-latest
    needs:
      - deploy-documentation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.EPITECH_REPOSITORY_LINK }}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
